spring:
  application:
   name: ScooterRentService
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  servlet:
    context-path: /api
jwt:
  secret: ${jwt-secret}
  expiration: 30000000
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
