spring:
  application:
   name: ScooterRentService
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: username
    password: password

  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: validate
